steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sarthi-repo/sarthi',
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/sarthi-repo/sarthi'
