# =====================================================================
# Sarthi - New Relic Agent Configuration
# =====================================================================

[newrelic]
# To change these parameters, use environment variables:
# - NEW_RELIC_LICENSE_KEY
# - NEW_RELIC_APP_NAME
# ---------------------------------------------------------------------
license_key = YOUR_NEW_RELIC_LICENSE_KEY
app_name = Sarthi-Backend-Prod
monitor_mode = true
log_file = stdout
log_level = info
ssl = true
transaction_tracer.enabled = true
transaction_tracer.transaction_threshold = apdex_f
error_collector.enabled = true
thread_profiler.enabled = true
