import json
from loguru import logger
from typing import Any, Dict, Optional
from openai import OpenAI
from app.core.config import settings
from app.services.llm_router import get_llm_completion
from app.agents.context import build_agent_system_prompt, enrich_agent_output, parse_json_response



class DatabaseModelGenerationAgent:
    """
    DatabaseModelGenerationAgent for Sarthi.
    Performs ORM model generation orchestration, entity schema design, migration path planning,
    persistence layer repository mapping, and validation schema mapping.
    """

    def __init__(self):
        self.api_key = settings.NVIDIA_API_KEY
        self.base_url = settings.NVIDIA_BASE_URL
        self.model = settings.NVIDIA_MODEL
        self.agent_name = "DatabaseModelGenerationAgent"

    def _get_client(self) -> OpenAI:
        return OpenAI(
            base_url=self.base_url,
            api_key=self.api_key,
            timeout=10.0
        )

    async def design(
        self,
        requirements: Dict[str, Any],
        db_architecture: Dict[str, Any],
        backend_architecture: Dict[str, Any],
        api_architecture: Dict[str, Any],
        auth_architecture: Dict[str, Any],
        validation_architecture: Dict[str, Any],
        optimization_architecture: Dict[str, Any],
        code_generation_planner: Dict[str, Any],
        global_project_context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Analyze requirements and upstream architectures to generate details of database models, migrations,
        repositories, validation schemas, and persistence optimization rules.
        """
        agent_inputs = {
            "requirements": requirements,
            "db_architecture": db_architecture,
            "backend_architecture": backend_architecture,
            "api_architecture": api_architecture,
            "auth_architecture": auth_architecture,
            "validation_architecture": validation_architecture,
            "optimization_architecture": optimization_architecture,
            "code_generation_planner": code_generation_planner,
            "global_project_context": global_project_context,
        }

        if not (settings.NVIDIA_API_KEY or settings.OPENROUTER_API_KEY or settings.GROQ_API_KEY or settings.GOOGLE_API_KEY):
            logger.warning("NVIDIA_API_KEY not configured. Using intelligent fallback database model persistence design.")
            return enrich_agent_output(
                self._get_fallback_database_model_generation(**agent_inputs),
                self.agent_name,
                agent_inputs
            )

        system_prompt = build_agent_system_prompt(
            self.agent_name,
            "Design production-grade database models, ORM classes mappings, migration sequences, validation schemas, and persistence repositories rules."
        )

        user_content = f"""
Analyze the following Sarthi inputs:
Requirements: {json.dumps(requirements, indent=2)}
Database Architecture: {json.dumps(db_architecture, indent=2)}
Backend Architecture: {json.dumps(backend_architecture, indent=2)}
API Architecture: {json.dumps(api_architecture, indent=2)}
Authentication Architecture: {json.dumps(auth_architecture, indent=2)}
Validation Architecture: {json.dumps(validation_architecture, indent=2)}
Optimization Architecture: {json.dumps(optimization_architecture, indent=2)}
Code Generation Planner: {json.dumps(code_generation_planner, indent=2)}
Global Project Context: {json.dumps(global_project_context or {}, indent=2)}

Return ONLY valid JSON in this exact format:
{{
  "status": "success",
  "persistence_generation_strategy": {{
    "orm_strategy": "e.g. SQLAlchemy declarative base models with async engine mappings.",
    "migration_strategy": "e.g. Autogenerated Alembic migration revisions in sequential dependency orders.",
    "validation_strategy": "e.g. Pydantic v2 validation models mapped strictly to SQLAlchemy model fields.",
    "repository_mapping_strategy": "e.g. Async generic repository pattern isolating SQLAlchemy session contexts."
  }},
  "generated_models": [
    {{
      "model_name": "e.g. User",
      "table_name": "e.g. users",
      "fields": [
        {{
          "name": "id",
          "type": "UUID",
          "primary_key": true,
          "nullable": false,
          "default": "uuid.uuid4"
        }}
      ],
      "relationships": [
        {{
          "target_model": "e.g. Portfolio",
          "relationship_type": "one-to-many",
          "backref": "owner",
          "cascade": "all, delete-orphan"
        }}
      ],
      "indexes": [
        {{
          "index_name": "idx_users_email",
          "fields": ["email"],
          "unique": true
        }}
      ]
    }}
  ],
  "relationship_generation": {{
    "foreign_keys": [
      {{
        "constrained_table": "portfolios",
        "constrained_column": "owner_id",
        "referenced_table": "users",
        "referenced_column": "id",
        "on_delete": "CASCADE"
      }}
    ],
    "many_to_many_mappings": [],
    "cascade_rules": [
      "Deleting a User cascades delete-orphan to all owned Portfolios."
    ]
  }},
  "migration_generation": {{
    "migration_groups": ["users_table_migration", "portfolios_table_migration"],
    "dependency_order": ["users_table_migration", "portfolios_table_migration"],
    "rollback_rules": [
      "Rollback drops the tables in reverse dependency order: portfolios, then users."
    ]
  }},
  "validation_schema_generation": {{
    "request_validation_models": [
      {{
        "schema_name": "UserCreate",
        "fields": ["name", "email", "password"]
      }}
    ],
    "response_validation_models": [
      {{
        "schema_name": "UserResponse",
        "fields": ["id", "name", "email"]
      }}
    ],
    "shared_validation_contracts": [
      "Pydantic schemas must share identity parameter formats directly with backend database entities."
    ]
  }},
  "repository_generation": {{
    "repository_targets": ["UserRepository", "PortfolioRepository"],
    "shared_persistence_layers": ["DatabaseSessionManager"],
    "async_repository_targets": ["AsyncUserRepository", "AsyncPortfolioRepository"]
  }},
  "authentication_persistence": {{
    "auth_models": ["UserAuthCredentials"],
    "session_models": ["UserSession"],
    "token_persistence_rules": [
      "Refresh tokens must be stored alongside session IDs and hashed in the DB."
    ]
  }},
  "optimization_generation": {{
    "index_generation_targets": ["idx_users_email"],
    "cache_compatible_models": ["User"],
    "high_frequency_models": ["Transaction"]
  }},
  "generation_dependencies": {{
    "blocking_models": ["User"],
    "shared_dependencies": ["BaseModelMixin"],
    "cross_module_dependencies": ["AuthSessionDependencies"]
  }},
  "future_generation_context": {{
    "important_notes_for_backend_generation": [
      "Always use async repository connections."
    ],
    "important_notes_for_api_generation": [
      "Map db response models directly to api schemas via from_attributes configurations."
    ],
    "important_notes_for_compilation_agents": [
      "Generate alembic.ini configuration maps during build."
    ]
  }}
}}
"""

        try:
            raw_response = await get_llm_completion(
                agent_name=self.agent_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content}
                ],
                temperature=0.1
            )
            raw_response = raw_response.strip()
            return enrich_agent_output(parse_json_response(raw_response), self.agent_name, agent_inputs)
        except Exception as e:
            logger.error(f"Failed to run DatabaseModelGenerationAgent: {e}")
            return enrich_agent_output(
                self._get_fallback_database_model_generation(**agent_inputs),
                self.agent_name,
                agent_inputs
            )

    def _get_fallback_database_model_generation(
        self,
        requirements: Dict[str, Any],
        db_architecture: Dict[str, Any],
        backend_architecture: Dict[str, Any],
        api_architecture: Dict[str, Any],
        auth_architecture: Dict[str, Any],
        validation_architecture: Dict[str, Any],
        optimization_architecture: Dict[str, Any],
        code_generation_planner: Dict[str, Any],
        global_project_context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Fallback logic that constructs ORM models, relationships, and migration schemas from
        the upstream architecture models.
        """
        entities = db_architecture.get("entities", []) if db_architecture else []
        entity_names = []
        for entity in entities:
            if isinstance(entity, str):
                entity_names.append(entity)
            elif isinstance(entity, dict) and entity.get("entity_name"):
                entity_names.append(entity["entity_name"])
        
        if not entity_names:
            req_entities = requirements.get("database_requirements", {}).get("entities", []) if requirements else []
            entity_names = [e for e in req_entities if e]
        if not entity_names:
            entity_names = ["User", "Item"]

        generated_models = []
        foreign_keys = []
        validation_request_models = []
        validation_response_models = []

        for name in entity_names:
            tbl_name = f"{name.lower()}s"
            fields = [
                {"name": "id", "type": "UUID", "primary_key": True, "nullable": False, "default": "uuid.uuid4"},
                {"name": "created_at", "type": "DateTime", "primary_key": False, "nullable": False, "default": "datetime.utcnow"}
            ]

            if name == "User":
                fields.append({"name": "email", "type": "String(255)", "primary_key": False, "nullable": False, "default": None})
                fields.append({"name": "hashed_password", "type": "String(255)", "primary_key": False, "nullable": False, "default": None})
            else:
                fields.append({"name": "name", "type": "String(255)", "primary_key": False, "nullable": False, "default": None})
                if "User" in entity_names:
                    fields.append({"name": "user_id", "type": "UUID", "primary_key": False, "nullable": True, "default": None})
                    foreign_keys.append({
                        "constrained_table": tbl_name,
                        "constrained_column": "user_id",
                        "referenced_table": "users",
                        "referenced_column": "id",
                        "on_delete": "CASCADE"
                    })

            relationships = []
            if name == "User":
                for other in entity_names:
                    if other != "User":
                        relationships.append({
                            "target_model": other,
                            "relationship_type": "one-to-many",
                            "backref": "user",
                            "cascade": "all, delete-orphan"
                        })
            else:
                if "User" in entity_names:
                    relationships.append({
                        "target_model": "User",
                        "relationship_type": "many-to-one",
                        "backref": tbl_name,
                        "cascade": ""
                    })

            indexes = []
            if name == "User":
                indexes.append({
                    "index_name": "idx_users_email",
                    "fields": ["email"],
                    "unique": True
                })

            generated_models.append({
                "model_name": name,
                "table_name": tbl_name,
                "fields": fields,
                "relationships": relationships,
                "indexes": indexes
            })

            # Mock Validation models
            validation_request_models.append({
                "schema_name": f"{name}Create",
                "fields": [f["name"] for f in fields if not f["primary_key"] and f["name"] != "created_at"]
            })
            validation_response_models.append({
                "schema_name": f"{name}Response",
                "fields": [f["name"] for f in fields]
            })

        migration_groups = [f"{name.lower()}s_migration" for name in entity_names]
        dependency_order = []
        # Ensure User migration runs before dependent ones
        if "User" in entity_names:
            dependency_order.append("users_migration")
        for item in entity_names:
            grp = f"{item.lower()}s_migration"
            if grp not in dependency_order:
                dependency_order.append(grp)

        return {
            "status": "success",
            "persistence_generation_strategy": {
                "orm_strategy": "SQLAlchemy declarative base class mapping utilizing async PG engines.",
                "migration_strategy": "Alembic autogenerated revisions with sequential constraint mapping checks.",
                "validation_strategy": "Pydantic v2 schemas validating request and response payloads matching DB data classes.",
                "repository_mapping_strategy": "Generic repositories wrapping db sessions with type-safe operations."
            },
            "generated_models": generated_models,
            "relationship_generation": {
                "foreign_keys": foreign_keys,
                "many_to_many_mappings": [],
                "cascade_rules": [
                    f"User cascades delete-orphan to {e}."
                    for e in entity_names if e != "User"
                ]
            },
            "migration_generation": {
                "migration_groups": migration_groups,
                "dependency_order": dependency_order,
                "rollback_rules": [
                    f"Drop tables in reverse dependency order: {', '.join(reversed(entity_names))}."
                ]
            },
            "validation_schema_generation": {
                "request_validation_models": validation_request_models,
                "response_validation_models": validation_response_models,
                "shared_validation_contracts": [
                    "Validate standard UUID formats.",
                    "Enforce non-empty field validators for required properties."
                ]
            },
            "repository_generation": {
                "repository_targets": [f"{name}Repository" for name in entity_names],
                "shared_persistence_layers": ["DatabaseSessionManager"],
                "async_repository_targets": [f"Async{name}Repository" for name in entity_names]
            },
            "authentication_persistence": {
                "auth_models": ["UserAuth"],
                "session_models": ["UserSession"],
                "token_persistence_rules": [
                    "Store refresh tokens in secure database entries.",
                    "Enforce strict token index lookups."
                ]
            },
            "optimization_generation": {
                "index_generation_targets": ["idx_users_email"],
                "cache_compatible_models": [e for e in entity_names if e in ["User", "Item"]] or ["User"],
                "high_frequency_models": [e for e in entity_names if e != "User"] or ["Item"]
            },
            "generation_dependencies": {
                "blocking_models": ["User"],
                "shared_dependencies": ["BaseModelMixin"],
                "cross_module_dependencies": ["AuthSessionDependencies"]
            },
            "future_generation_context": {
                "important_notes_for_backend_generation": [
                    "Integrate async database contexts."
                ],
                "important_notes_for_api_generation": [
                    "Configure ORM serialization bindings."
                ],
                "important_notes_for_compilation_agents": [
                    "Validate Alembic connection environments settings."
                ]
            }
        }
